name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: python:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check mypy
      run: mypy main/

    - name: Check black
      run: black --diff --check main/

    - name: Check isort
      run: isort --check-only main/

    - name: Check flake8
      run: flake8 main/

    - name: Run unittest
      run: pytest tests
